### ISSUE TITLE
打开页面报错

### ISSUE THREAD

**Issue by yushilong** [S4mpl3r/django-ecommerce#1]
![image](https://github.com/S4mpl3r/django-ecommerce/assets/5087094/3b65f17a-08f1-4d52-b8d0-90929b5da4d8)

**Comment by S4mpl3r** [comment]
Hello there!
Thank you for checking out this repo. The issue is because your database is empty, you need to populate it with some dummy data for this to work. 
To solve the issue, first create a superuser using `python manage.py createsuperuser` command, then log in at `http://localhost:8000/admin/` using your credentials and add some Items and Categories. Then try again.
Feel free to reach out if the issue persists.
